language: android
jdk: oraclejdk8
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
android:
  components:
  - build-tools-28.0.3
  - android-28
before_script:
- openssl aes-256-cbc -K $encrypted_e52ce8830a54_key -iv $encrypted_e52ce8830a54_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- git clone https://github.com/flutter/flutter.git -b beta
- export PATH=./flutter/bin:$PATH
script:
- flutter packages get
- flutter test
- flutter build apk
cache:
  directories:
  - "$HOME/.pub-cache"
