matrix:
  # allow_failures:
  #   - env: JOB=test-ipa-long-shot
  include:
    - env: JOB=test-apk
      language: android
      jdk: oraclejdk8 # Android sdkmanager doesn't support jdk 9+
      licenses:
        - android-sdk-preview-license-.+
        - android-sdk-license-.+
        - google-gdk-license-.+
      android:
        components:
          - build-tools-28.0.3
          - android-28
      before_install:
        - bundle install --gemfile=android/Gemfile   
      before_script:
        - openssl aes-256-cbc -K $encrypted_2db283701f8c_key -iv $encrypted_2db283701f8c_iv 
          -in secrets.tar.enc -out secrets.tar -d
        - tar xvf secrets.tar
        - if [  ! -d "flutter" ] ; then git clone https://github.com/flutter/flutter.git -b beta; fi;
        - export PATH=./flutter/bin:$PATH
        - flutter upgrade
      script:
        - flutter pub get
        - flutter test 
        - flutter build apk --verbose
        - cd android && bundle exec fastlane android deploy_beta
        
    # I just needed to know what was missing from 
    # - env: JOB=test-ipa-long-shot
    #   language: objective-c
    #   osx_image: xcode10.2
    #   before_script:
    #     - git clone https://github.com/flutter/flutter.git -b beta
    #     - export PATH=./flutter/bin:$PATH
    #   script:
    #     - flutter pub get
    #     - flutter build ios --no-codesign --verbose 

cache:
  bundler: true
  directories:
    - "$HOME/.pub-cache"
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
    - "$HOME/.android/build-cache"
    - "$HOME/flutter"

