include: package:extra_pedantic/analysis_options_flutter.yaml

analyzer:
  exclude:
    - lib/generated/l10n.dart
    - lib/generated/intl/messages_*.dart
    - lib/src/**/*g.dart
    - lib/src/models/**/*.g.dart

linter:
  rules:
    - prefer_const_constructors
    - avoid_relative_lib_imports
    - prefer_relative_imports
