include: package:extra_pedantic/analysis_options_flutter.yaml

analyzer:
  exclude:
    - lib/generated/l10n.dart
    - lib/generated/intl/messages_*.dart
    - lib/src/**/*g.dart
    - lib/src/models/**/*.g.dart

linter:
  rules:
    - prefer_single_quotes
    - unnecessary_brace_in_string_interps
    - sort_constructors_first
    - unnecessary_this
