name: navis
description: Cephalon Navis is an Android app inspired by Warframe Hub.
version: 1.5.11+72

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  worldstate_api_model:
    git: https://github.com/SlayerOrnstein/worldstate_model.git
  warframe_items_model:
    git: https://github.com/SlayerOrnstein/warframe_item_models.git
  equatable: ^1.0.3
  flutter_bloc: ^3.2.0
  firebase_crashlytics: ^0.1.2+5
  flutter_custom_tabs: ^0.6.0
  hydrated_bloc: ^3.0.0
  intl: ^0.16.0
  package_info: ^0.4.0+13
  firebase_messaging: ^6.0.9
  cached_network_image: ^2.0.0
  flutter_svg: ^0.17.1
  floating_search_bar: ^0.3.0
  flutter_sticky_header: ^0.4.0
  hive: ^1.3.0
  get_it: ^3.1.0
  dartz: ^0.8.9
  data_connection_checker: ^0.3.4
  youtube_player_flutter: ^6.0.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.6.3
  mockito: ^4.1.1
  extra_pedantic: ^1.1.1
  intl_translation: ^0.17.7

flutter:
  uses-material-design: true
  fonts:
    - family: NavisSysIcons
      fonts:
        - asset: assets/icons/NavisSysIcons.ttf
    - family: PlatformIcons
      fonts:
        - asset: assets/icons/PlatformIcons.ttf
    - family: RelicIcons
      fonts:
        - asset: assets/icons/RelicIcons.ttf
    - family: FactionIcons
      fonts:
        - asset: assets/icons/FactionIcons.ttf
    - family: SyndicateIcons
      fonts:
        - asset: assets/icons/SyndicateIcons.ttf
  assets:
    - assets/wfcd_banner.svg
    - assets/enemies/corrupted/
    - assets/enemies/grineer/
    - assets/enemies/corpus/
    - assets/enemies/infestation/
    - assets/enemies/stalker/
    - assets/skyboxes/
    - assets/event_info.json
    # - assets/maps/
    # - assets/maps/imgs/
