name: navis
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.7
  flutter_youtube: ^1.1.4
  codable: ^1.0.0
  rxdart: ^0.20.0
  shared_preferences: ^0.4.3
  flutter_custom_tabs: ^0.4.0
  flutter_sequence_animation: ^3.0.1
  flutter_map: ^0.4.0
  flutter_svg: ^0.7.0+1
  chewie: ^0.8.0
  cached_network_image: ^0.5.1
  background_fetch: ^0.1.1
  flutter_crashlytics:
    path: flutter_crashlytics/

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    #- assets/acolytes/
    - assets/general/
    - assets/platforms/
    - assets/factions/
    - assets/sigils/
    - assets/relics/

    #Plains of Eidolon map tiles
    #- assets/plains/0/
    #- assets/plains/1/
    #- assets/plains/2/

    #Orb Vallis Map tiles
    #- assets/vallis/1/
    #- assets/vallis/2/
    #- assets/vallis/3/
    #- assets/vallis/4/