name: navis
description: Cephalon Navis is an Android app inspired by Warframe Hub.
version: 1.1.0+7

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  background_fetch: ^0.1.1
  bloc: ^0.9.3
  chewie: ^0.9.5
  codable: ^1.0.0
  dots_indicator: ^0.0.4
  equatable: ^0.2.0
  firebase_messaging: ^3.0.1
  cached_network_image: ^0.6.1
  flutter_bloc: ^0.6.3
  flutter_crashlytics: ^0.2.1
  flutter_custom_tabs: ^0.5.0
  flutter_map: ^0.4.0
  flutter_material_color_picker: ^0.0.5
  flutter_svg: ^0.10.4
  flutter_villains: ^1.2.0
  intl: ^0.15.7
  shared_preferences: ^0.5.1+1
  sticky_headers: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.5.1
  mockito: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Standing
      fonts:
        - asset: assets/general/Standing.ttf
    - family: VoidTear
      fonts:
        - asset: assets/general/VoidTear.ttf
  assets:
    - assets/general/
    - assets/platforms/
    - assets/factions/
    - assets/sigils/
    - assets/relics/
