name: navis
description: Cephalon Navis is an Android app inspired by Warframe Hub.
version: 1.2.25+48

dependencies:
  flutter:
    sdk: flutter
  bloc: ^0.15.0
  equatable: ^0.4.0
  flutter_bloc: ^0.21.0
  firebase_crashlytics: ^0.1.0+2
  flutter_custom_tabs: ^0.6.0
  hydrated_bloc: ^0.4.0
  intl: ^0.15.8
  package_info: ^0.4.0+6
  shared_preferences: ^0.5.3+4
  firebase_messaging: ^5.1.2
  cached_network_image: ^1.1.1
  flutter_svg: ^0.14.0
  simple_animations: ^1.3.3
  floating_search_bar: ^0.2.0
  json_annotation: ^3.0.0
  worldstate_model:
    git: https://github.com/SlayerOrnstein/worldstate_model.git
  wfcd_api_wrapper:
    git: https://github.com/SlayerOrnstein/wfcd_api_wrapper.git
  firebase_performance: ^0.3.0+4
  overlay_support: ^1.0.1
  flutter_sticky_header: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.6.1
  mockito: ^4.1.0

builders:
  json_serializable: ^3.2.0

flutter:
  uses-material-design: true
  fonts:
    - family: Standing
      fonts:
        - asset: assets/general/Standing.ttf
    - family: Sortie
      fonts:
        - asset: assets/general/Sortie.ttf
    - family: VoidFissure
      fonts:
        - asset: assets/general/VoidFissure.ttf
  assets:
    - assets/general/
    - assets/factions/Corrupted/
    - assets/factions/Grineer/
    - assets/factions/Corpus/
    - assets/factions/Infestation/
    - assets/platforms/
    - assets/sigils/
    - assets/relics/
    - assets/skyboxes/
    #- assets/maps/
    #- assets/maps/imgs/
