name: navis
description: Cephalon Navis is an Android app inspired by Warframe Hub.
version: 1.2.5+28

dependencies:
  flutter:
    sdk: flutter
  bloc: ^0.14.2
  hydrated_bloc: ^0.2.1
  codable: ^1.0.0
  equatable: ^0.2.5
  firebase_lumberdash: ^1.0.1
  flutter_bloc: ^0.15.1
  firebase_crashlytics: ^0.0.4+4
  flutter_custom_tabs: ^0.6.0
  #flutter_map: ^0.5.3+1
  intl: ^0.15.8
  lumberdash: ^1.0.3
  package_info: ^0.4.0+4
  shared_preferences: ^0.5.2+2
  sticky_headers: ^0.1.7
  firebase_messaging: ^5.0.2
  cached_network_image: ^0.8.0
  flutter_svg: ^0.13.0+2
  simple_animations: ^1.3.0
  get_it: ^1.0.3
  floating_search_bar: ^0.2.0

dependency_overrides:
  path_provider: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.6.1
  mockito: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Standing
      fonts:
        - asset: assets/general/Standing.ttf
    - family: Sortie
      fonts:
        - asset: assets/general/Sortie.ttf
    - family: VoidFissure
      fonts:
        - asset: assets/general/VoidFissure.ttf        
  assets:
    - assets/general/
    - assets/platforms/
    - assets/factions/Corrupted/
    - assets/factions/Grineer/
    - assets/factions/Corpus/
    - assets/factions/Infestation/
    - assets/sigils/
    - assets/relics/
    - assets/skyboxes/
    - assets/slim.json
    #- assets/maps/
    #- assets/maps/imgs/
