name: navis
version: 1.9.2+94
description: Cephalon Navis is an Android app inspired by Warframe Hub.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  bloc: ^6.0.1
  equatable: ^1.2.2
  flutter_bloc: ^6.0.0
  firebase_crashlytics: ^0.1.3+3
  flutter_custom_tabs: ^0.6.0
  hydrated_bloc: ^6.0.0
  intl: ^0.16.0
  intl_translation: ^0.17.7
  package_info: ^0.4.0+17
  firebase_messaging: ^6.0.16
  cached_network_image: ^2.2.0+1
  flutter_svg: ^0.18.0
  flutter_sticky_header: ^0.4.2
  hive: ^1.4.1+1
  get_it: ^4.0.2
  data_connection_checker: ^0.3.4
  youtube_explode_dart: ^1.4.1+1
  chewie: ^0.9.10
  dartz: ^0.9.1
  flutter_staggered_grid_view: ^0.3.1
  supercharged: ^1.7.0
  flutter_brand_icons: ^1.1.0
  warframestat_api_models:
    git: https://github.com/SlayerOrnstein/warframestat_api_models.git
  wfcd_client:
    git: https://github.com/SlayerOrnstein/wfcd_client.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.3
  mockito: ^4.1.1
  extra_pedantic: ^1.2.0

flutter:
  uses-material-design: true
  fonts:
    - family: NavisSysIcons
      fonts:
        - asset: assets/icons/NavisSysIcons.ttf
    - family: PlatformIcons
      fonts:
        - asset: assets/icons/PlatformIcons.ttf
    - family: RelicIcons
      fonts:
        - asset: assets/icons/RelicIcons.ttf
    - family: FactionIcons
      fonts:
        - asset: assets/icons/FactionIcons.ttf
    - family: SyndicateGlyphs
      fonts:
        - asset: assets/icons/SyndicateGlyphs.ttf
  assets:
    # - assets/wfcd_banner.svg
    - assets/Derelict.webp
    - assets/skyboxes/Void.webp
    - assets/event_info.json
    - assets/wfcd_logo_color.svg
    - assets/skybox_nodes.json

flutter_intl:
  enabled: true
  class_name: NavisLocalizations
