name: navis
version: 2.3.10+143
description: Cephalon Navis is an Android app inspired by Warframe Hub.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  wfcd_client:
    git: https://github.com/SlayerOrnstein/wfcd_client.git
  bloc: ^7.0.0
  cached_network_image: ^3.0.0-nullsafety
  chewie: ^1.0.0
  equatable: ^2.0.0
  firebase_core: ^1.1.0
  firebase_messaging: ^9.1.3
  flutter_bloc: ^7.0.0
  flutter_sticky_header: ^0.6.0
  flutter_svg: ^0.22.0
  flutter_web_browser: ^0.14.0
  get_it: ^7.1.2
  hive: ^2.0.4
  hydrated_bloc: ^7.0.0
  internet_connection_checker: ^0.0.1
  intl: ^0.17.0
  matomo: ^0.1.2
  oxidized: ^4.2.0
  package_info: ^2.0.0
  responsive_builder: ^0.4.1
  sentry_flutter: ^5.0.0
  simple_icons: ^4.22.0
  supercharged: ^2.0.0
  youtube_explode_dart: ^1.9.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.2
  test: ^1.16.5
  very_good_analysis: ^2.0.3

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: NavisSysIcons
      fonts:
        - asset: assets/icons/NavisSysIcons.ttf
    - family: PlatformIcons
      fonts:
        - asset: assets/icons/PlatformIcons.ttf
    - family: RelicIcons
      fonts:
        - asset: assets/icons/RelicIcons.ttf
    - family: FactionIcons
      fonts:
        - asset: assets/icons/FactionIcons.ttf
    - family: SyndicateGlyphs
      fonts:
        - asset: assets/icons/SyndicateGlyphs.ttf
  assets:
    - assets/Derelict.webp
    - assets/event_info.json
    - assets/wfcd_logo_color.svg
    # - assets/mod_frames/
