name: navis
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.7
  flutter_youtube: ^1.1.4
  codable: ^1.0.0
  rxdart: ^0.19.0
  shared_preferences: ^0.4.3
  flutter_custom_tabs: ^0.4.0
  flutter_map: ^0.2.0
  flutter_svg: ^0.6.3
  sentry: ^2.1.1
  chewie: ^0.8.0
  cached_network_image: ^0.5.0+1
  timeago: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/sigils/
    - assets/acolytes/
    - assets/hotfix.jpg

  fonts:
    - family: Factions
      fonts:
        - asset: assets/icons/Factions.ttf
    - family: Icons
      fonts:
        - asset: assets/icons/Icons.ttf
    - family: Relics
      fonts:
        - asset: assets/icons/Relics.ttf
    - family: Platforms
      fonts:
        - asset: assets/icons/Platforms.ttf
    - family: Syndicates
      fonts:
        - asset: assets/icons/Syndicates.ttf
    - family: Nightmare
      fonts:
        - asset: assets/icons/Nightmare.ttf
    - family: archwing
      fonts:
        - asset: assets/icons/archwing.ttf
    - family: invasions
      fonts:
        - asset: assets/icons/invasions.ttf