name: navis
version: 2.3.7+140
description: Cephalon Navis is an Android app inspired by Warframe Hub.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  wfcd_client:
    git: https://github.com/SlayerOrnstein/wfcd_client.git
  bloc: ^7.0.0
  cached_network_image: ^3.0.0-nullsafety
  chewie: ^1.0.0
  dartz: ^0.10.0-nullsafety.1
  internet_connection_checker: ^0.0.1
  equatable: ^2.0.0
  firebase_core: ^1.0.2
  firebase_messaging: ^9.1.0
  flutter_bloc: ^7.0.0
  flutter_sticky_header:
    git:
      url: https://github.com/Femtopedia/flutter_sticky_header.git
      ref: master
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_web_browser: ^0.14.0
  get_it: ^6.0.0
  hive: ^2.0.2
  hydrated_bloc: ^7.0.0
  intl: ^0.17.0
  matomo:
    git: https://github.com/SlayerOrnstein/dart-matomo.git
  package_info: ^2.0.0
  responsive_builder: ^0.4.1
  sentry_flutter: ^5.0.0
  simple_icons: ^4.17.0
  supercharged: ^2.0.0
  youtube_explode_dart: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.0.0
  mocktail: ^0.1.1
  test: ^1.16.5

# dependency_overrides:
#   equatable: ^2.0.0
#   intl: ^0.17.0
#   path_provider: ^2.0.1
#   json_annotation: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: NavisSysIcons
      fonts:
        - asset: assets/icons/NavisSysIcons.ttf
    - family: PlatformIcons
      fonts:
        - asset: assets/icons/PlatformIcons.ttf
    - family: RelicIcons
      fonts:
        - asset: assets/icons/RelicIcons.ttf
    - family: FactionIcons
      fonts:
        - asset: assets/icons/FactionIcons.ttf
    - family: SyndicateGlyphs
      fonts:
        - asset: assets/icons/SyndicateGlyphs.ttf
  assets:
    - assets/Derelict.webp
    - assets/event_info.json
    - assets/wfcd_logo_color.svg
    - assets/mod_frames/
