name: navis
version: 1.10.0+98
description: Cephalon Navis is an Android app inspired by Warframe Hub.
dependencies: 
  cupertino_icons: ^0.1.3
  bloc: ^6.0.1
  equatable: ^1.2.2
  flutter_bloc: ^6.0.1
  firebase_crashlytics: ^0.1.3+3
  flutter_custom_tabs: ^0.6.0
  hydrated_bloc: ^6.0.1
  intl: ^0.16.0
  intl_translation: ^0.17.7
  package_info: ^0.4.0+17
  firebase_messaging: ^6.0.16
  cached_network_image: ^2.2.0+1
  flutter_svg: ^0.18.0
  floating_search_bar: ^0.3.0
  flutter_sticky_header: ^0.4.0
  hive: ^1.1.1
  hive_flutter: ^0.3.0+2
  flutter_brand_icons: ^1.1.0
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  wfcd_client: 
    git: https://github.com/SlayerOrnstein/wfcd_client.git
  warframestat_api_models: 
    git: https://github.com/SlayerOrnstein/warframestat_api_models.git
dev_dependencies: 
  test: ^1.6.3
  bloc_test: ^7.0.0
  mockito: ^4.1.1
  flutter_native_splash: ^0.1.9
  flutter_test: 
    sdk: flutter
  flutter_driver: 
    sdk: flutter
flutter: 
  fonts: 
    - 
      family: AppIcons
      fonts: 
        - 
          asset: assets/icons/AppIcons.ttf
    - 
      family: PlatformIcons
      fonts: 
        - 
          asset: assets/icons/PlatformIcons.ttf
    - 
      family: RelicIcons
      fonts: 
        - 
          asset: assets/icons/RelicIcons.ttf
    - 
      family: FactionIcons
      fonts: 
        - 
          asset: assets/icons/FactionIcons.ttf
    - 
      family: SyndicateGlyphs
      fonts: 
        - 
          asset: assets/icons/SyndicateGlyphs.ttf
  assets: 
    - assets/icons/
    - assets/wfcd_logo_color.svg
    - assets/enemys/Corrupted/
    - assets/enemys/Grineer/
    - assets/enemys/Corpus/
    - assets/enemys/Infestation/
    - assets/Derelict.webp
    - assets/skyboxes/Void.webp
  uses-material-design: true
flutter_intl: 
  class_name: NavisLocalizations
  enabled: true
flutter_native_splash: 
  image: assets/nightmare.png
  color: FFFFFF
  android: false
