name: navis
version: 1.13.0+109
description: Cephalon Navis is an Android app inspired by Warframe Hub.
dependencies:
  bloc: ^6.0.1
  cached_network_image: ^2.2.0+1
  cupertino_icons: ^1.0.0
  equatable: ^1.2.2
  firebase_core: ^0.5.0+1
  firebase_crashlytics: ^0.2.1+1
  firebase_messaging: ^7.0.3
  floating_search_bar: ^0.3.0
  flutter_bloc: ^6.0.6
  flutter_brand_icons: ^1.1.0
  flutter_custom_tabs: ^0.6.0
  flutter_sticky_header: ^0.5.0
  flutter_svg: ^0.19.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.0+2
  hydrated_bloc: ^6.0.2
  intl: ^0.16.0
  intl_translation: ^0.17.7
  package_info: ^0.4.0+17
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  warframestat_api_models:
    git: https://github.com/SlayerOrnstein/warframestat_api_models.git
  wfcd_client:
    git: https://github.com/SlayerOrnstein/wfcd_client.git
dev_dependencies:
  bloc_test: ^7.0.0
  flutter_native_splash: ^0.1.9
  mockito: ^4.1.1
  test: ^1.6.3
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
enviroment:
  sdk: ">=2.10.0 < 3.0.0"
flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/icons/AppIcons.ttf
    - family: PlatformIcons
      fonts:
        - asset: assets/icons/PlatformIcons.ttf
    - family: RelicIcons
      fonts:
        - asset: assets/icons/RelicIcons.ttf
    - family: FactionIcons
      fonts:
        - asset: assets/icons/FactionIcons.ttf
    - family: SyndicateGlyphs
      fonts:
        - asset: assets/icons/SyndicateGlyphs.ttf
  assets:
    - assets/icons/
    - assets/wfcd_logo_color.svg
    - assets/enemys/Corrupted/
    - assets/enemys/Grineer/
    - assets/enemys/Corpus/
    - assets/enemys/Infestation/
    - assets/Derelict.webp
    - assets/skyboxes/Void.webp
