name: navis
version: 2.3.2+135
description: Cephalon Navis is an Android app inspired by Warframe Hub.
publish_to: none

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  wfcd_client:
    git: https://github.com/SlayerOrnstein/wfcd_client.git
  bloc: ^6.1.3
  cached_network_image: ^2.4.1
  chewie: ^1.0.0
  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  # equatable: ^1.2.6
  firebase_core: ^1.0.0
  firebase_messaging: ^9.0.0
  flutter_bloc: ^6.1.3
  flutter_brand_icons: ^1.1.0
  flutter_sticky_header: ^0.5.0
  flutter_svg: ^0.19.3
  flutter_web_browser: ^0.13.0
  get_it: ^6.0.0
  hive: ^1.4.4+1
  hydrated_bloc: ^6.1.0
  # intl: ^0.17.0
  matomo: ^0.0.9
  package_info: ^0.4.0+13
  responsive_builder: ^0.3.0
  sentry_flutter: ^4.0.0
  supercharged: ^2.0.0
  youtube_explode_dart: ^1.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.0.0
  mockito: ^4.1.4
  test: ^1.16.0-nullsafety.5

dependency_overrides:
  equatable: ^2.0.0
  intl: ^0.17.0
  path_provider: ^2.0.1
  json_annotation: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: NavisSysIcons
      fonts:
        - asset: assets/icons/NavisSysIcons.ttf
    - family: PlatformIcons
      fonts:
        - asset: assets/icons/PlatformIcons.ttf
    - family: RelicIcons
      fonts:
        - asset: assets/icons/RelicIcons.ttf
    - family: FactionIcons
      fonts:
        - asset: assets/icons/FactionIcons.ttf
    - family: SyndicateGlyphs
      fonts:
        - asset: assets/icons/SyndicateGlyphs.ttf
  assets:
    - assets/Derelict.webp
    - assets/event_info.json
    - assets/wfcd_logo_color.svg
    - assets/mod_frames/
