name: navis
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.7
  flutter_youtube: ^1.1.1
  codable: ^1.0.0
  rxdart: ^0.18.1
  shared_preferences: ^0.4.3
  flutter_custom_tabs: ^0.4.0
  flutter_map: ^0.1.3
  sentry: ^2.1.1
  chewie: ^0.7.0
  cached_network_image: ^0.4.2
  timeago: ^2.0.8
  android_job_scheduler:
    path: android_job_scheduler/

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  http: ^0.12.0

flutter:
  uses-material-design: true
  assets:
    - assets/acolytes/
    - assets/hotfix.jpg
    - assets/plains/0/0/
    - assets/plains/1/0/
    - assets/plains/1/1/
    - assets/plains/2/0/
    - assets/plains/2/1/
    - assets/plains/2/2/
    - assets/plains/2/3/
    - assets/plains/3/0/
    - assets/plains/3/1/
    - assets/plains/3/2/
    - assets/plains/3/3/
    - assets/plains/3/4/
    - assets/plains/3/5/
    - assets/plains/3/6/
    - assets/plains/3/7/

  fonts:
    - family: Factions
      fonts:
        - asset: assets/icons/Factions.ttf
    - family: Icons
      fonts:
        - asset: assets/icons/Icons.ttf
    - family: Relics
      fonts:
        - asset: assets/icons/Relics.ttf
    - family: Platforms
      fonts:
        - asset: assets/icons/Platforms.ttf
    - family: Syndicates
      fonts:
        - asset: assets/icons/Syndicates.ttf
    - family: Nightmare
      fonts:
        - asset: assets/icons/Nightmare.ttf
    - family: archwing
      fonts:
        - asset: assets/icons/archwing.ttf
    - family: invasions
      fonts:
        - asset: assets/icons/invasions.ttf