name: navis
version: 1.11.2+102
description: Cephalon Navis is an Android app inspired by Warframe Hub.

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^6.0.1
  cached_network_image: ^2.2.0+1
  chewie: ^0.9.10
  data_connection_checker: ^0.3.4
  dartz: ^0.9.1
  equatable: ^1.2.2
  flutter_brand_icons: ^1.1.0
  firebase_core: ^0.5.0
  firebase_messaging: ^7.0.2
  firebase_crashlytics: ^0.2.1
  flutter_bloc: ^6.0.0
  flutter_custom_tabs: ^0.6.0
  flutter_local_notifications: ^2.0.0+1
  flutter_staggered_grid_view: ^0.3.1
  flutter_sticky_header: ^0.5.0
  flutter_svg: ^0.19.0
  hive: ^1.4.4+1
  hydrated_bloc: ^6.0.0
  intl: ^0.16.1
  intl_translation: ^0.17.7
  get_it: ^5.0.1
  package_info: ^0.4.0+17
  responsive_builder: ^0.3.0
  supercharged: ^1.7.0
  warframestat_api_models:
    git: https://github.com/SlayerOrnstein/warframestat_api_models.git
  wfcd_client:
    git: https://github.com/SlayerOrnstein/wfcd_client.git
  youtube_explode_dart: ^1.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  extra_pedantic: ^1.2.0
  mockito: ^4.1.2
  test: ^1.14.3

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: NavisSysIcons
      fonts:
        - asset: assets/icons/NavisSysIcons.ttf
    - family: PlatformIcons
      fonts:
        - asset: assets/icons/PlatformIcons.ttf
    - family: RelicIcons
      fonts:
        - asset: assets/icons/RelicIcons.ttf
    - family: FactionIcons
      fonts:
        - asset: assets/icons/FactionIcons.ttf
    - family: SyndicateGlyphs
      fonts:
        - asset: assets/icons/SyndicateGlyphs.ttf
  assets:
    - assets/Derelict.webp
    - assets/skyboxes/Void.webp
    - assets/event_info.json
    - assets/wfcd_logo_color.svg
    - assets/skybox_nodes.json
