name: navis
description: Cephalon Navis is an Android app inspired by Warframe Hub.
version: 1.5.2+63

dependencies:
  flutter:
    sdk: flutter
  bloc: ^2.0.0
  equatable: ^0.6.0
  flutter_bloc: ^2.0.0
  firebase_crashlytics: ^0.1.0+3
  flutter_custom_tabs: ^0.6.0
  hydrated_bloc: ^2.0.0
  intl: ^0.16.0
  package_info: ^0.4.0+10
  firebase_messaging: ^5.1.6
  cached_network_image: ^1.1.3
  flutter_svg: ^0.14.3
  floating_search_bar: ^0.2.0
  flutter_sticky_header: ^0.4.0
  worldstate_model:
    git: https://github.com/SlayerOrnstein/worldstate_model.git
  wfcd_api_wrapper:
    git: https://github.com/SlayerOrnstein/wfcd_api_wrapper.git
  warframe_items_model:
    git: https://github.com/SlayerOrnstein/warframe_item_models.git
  hive: ^1.1.1
  hive_flutter: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.6.3
  bloc_test: ^2.0.0
  mockito: ^4.1.1

flutter:
  uses-material-design: true
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/icons/AppIcons.ttf
    - family: PlatformIcons
      fonts:
        - asset: assets/icons/PlatformIcons.ttf
    - family: RelicIcons
      fonts:
        - asset: assets/icons/RelicIcons.ttf
    - family: FactionIcons
      fonts:
        - asset: assets/icons/FactionIcons.ttf
    - family: SyndicateIcons
      fonts:
        - asset: assets/icons/SyndicateIcons.ttf
  assets:
    - assets/icons/
    - assets/wfcd_banner.svg
    - assets/enemys/Corrupted/
    - assets/enemys/Grineer/
    - assets/enemys/Corpus/
    - assets/enemys/Infestation/
    - assets/skyboxes/
    #- assets/maps/
    #- assets/maps/imgs/
