name: navis
description: Cephalon Navis is an Android app inspired by Warframe Hub.
version: 2.0.0+95

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  warframestat_api_models:
    git: https://github.com/SlayerOrnstein/warframestat_api_models.git
  equatable: ^1.2.0
  cupertino_icons: ^0.1.3
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  firebase_crashlytics: ^0.1.3+3
  flutter_custom_tabs: ^0.6.0
  hydrated_bloc: ^4.1.1
  intl: ^0.16.1
  package_info: ^0.4.0+18
  firebase_messaging: ^6.0.16
  cached_network_image: ^2.2.0+1
  flutter_svg: ^0.17.4
  flutter_sticky_header: ^0.4.2
  hive: ^1.4.1+1
  get_it: ^4.0.2
  data_connection_checker: ^0.3.4
  youtube_explode_dart: ^1.0.0
  chewie: ^0.9.10
  dartz: ^0.9.1
  flutter_staggered_grid_view: ^0.3.0
  supercharged: ^1.6.0
  flutter_brand_icons: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.14.3
  mockito: ^4.1.1
  extra_pedantic: ^1.2.0
  intl_translation: ^0.17.9

flutter:
  uses-material-design: true
  fonts:
    - family: NavisSysIcons
      fonts:
        - asset: assets/icons/NavisSysIcons.ttf
    - family: PlatformIcons
      fonts:
        - asset: assets/icons/PlatformIcons.ttf
    - family: RelicIcons
      fonts:
        - asset: assets/icons/RelicIcons.ttf
    - family: FactionIcons
      fonts:
        - asset: assets/icons/FactionIcons.ttf
    - family: SyndicateGlyphs
      fonts:
        - asset: assets/icons/SyndicateGlyphs.ttf
  assets:
    - assets/wfcd_banner.svg
    # - assets/enemies/corrupted/
    # - assets/enemies/grineer/
    # - assets/enemies/corpus/
    # - assets/enemies/infestation/
    - assets/enemies/stalker/
    - assets/Derelict.webp
    - assets/skyboxes/Void.webp
    - assets/event_info.json
    - assets/wfcd_logo_color.svg
    - assets/skybox_nodes.json
    # - assets/maps/
    # - assets/maps/imgs/

flutter_intl:
  enabled: true
  class_name: NavisLocalizations
