name: warframe_items_model
description: Models for Warframe items
version: 1.2.0
author: Ludwig <blacklightinglr@gmail.com>

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.1
  equatable: ^1.1.1
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.8.0+1
  test: ^1.6.0
  build_runner: ^1.6.7
  json_serializable: ^3.2.5
  extra_pedantic: ^1.2.0
