name: Deploy
on:
  release:
    types: [created]
jobs:
  android-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Decode signing key and services json
        run: |
          flutter pub get
          flutter build apk --split-per-abi
          flutter clean # Cleaning before builds help remove an problems in between them
          flutter build appbundle
      - name: Build App bundle
        run: flutter build appbundle
      - name: Google Play Store Deploy
        uses: maierj/fastlane-action@v1
        with:
          lane: beta
          subdirectory: android
      - name: Clean build directory
        run: flutter clean
      - name: Build split apks per abi
        run: flutter build apk --split-per-abi
      - name: Github Releases Deploy
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          file: "build/app/outputs/apk/release/*.apk"
          tags: true
  ios-release: # Github's MacOS images come with fastlane preinstalled
    runs-on: macos-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Decode signing key and services json
        run: base64 -d <<< $TENNO_FIREBASE > android/app/google-services.json
      - name: Build ios using flutter
        run: flutter build ios
      - name: Deploy to App Store
        run: cd ios && fastlane lane beta
      - name: Github Releases Deploy
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          file: "build/app/outputs/apk/release/*.apk"
          tags: true
