name: Release
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - uses: cedx/setup-dart@v2
      - name: Install Dart packages
        run: pub global activate pubspec_version
      - name: Set execute permissions for versioning script
        run: chmod +x deploy.sh
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
