name: Release
on:
  push:
    branches:
      - master
      - n2.0
  pull_request:
    branches:
      - master
      - n2.0
jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cedx/setup-dart@v2
      - name: Install Dart packages
        run: pub global activate pubspec_version
      - name: Set execute permissions for versioning script
        run: chmod +x deploy.sh
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dry_run: true
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/git
